import { Router } from 'express';
import authRoutes from '../modules/auth/route';
import usersRoutes from '../modules/users/route';
import rolesRoutes from '../modules/roles/route';
import settingsRoutes from '../modules/settings/route';
import fiscalRoutes from '../modules/fiscal/route';
import accountRoutes from '../modules/accounts/route';
import journalRoutes from '../modules/journals/route';
import partiesRoutes from '../modules/parties/route';
import customersRoutes from '../modules/customers/route';
import suppliersRoutes from '../modules/suppliers/route';
import quotesRoutes from '../modules/quotes/route';
import salesReturnsRoutes from '../modules/sales-returns/route';
import invoiceRoutes from '../modules/invoices/route';
import paymentRoutes from '../modules/payments/route';
import bankRoutes from '../modules/banks/route';
import assetRoutes from '../modules/assets/route';
import budgetRoutes from '../modules/budgets/route';
import taxRoutes from '../modules/taxes/route';
import reportRoutes from '../modules/reports/route';
import auditRoutes from '../modules/audit-logs/route';
import fiscalYearsRoutes from '../modules/fiscal-years/route';
import periodsRoutes from '../modules/periods/route';
import bankTransactionsRoutes from '../modules/bank-transactions/route';
import assetCategoriesRoutes from '../modules/asset-categories/route';
import depreciationRoutes from '../modules/depreciation/route';
import accountingRoutes from '../modules/accounting/route';
import centralRoutes from '../modules/central/route';
import taxCodesRoutes from '../modules/tax-codes/route';
import taxDeclarationsRoutes from '../modules/tax-declarations/route';
import purchaseOrdersRoutes from '../modules/purchase-orders/route';
import purchaseRequestsRoutes from '../modules/purchase-requests/route';
import purchaseReturnsRoutes from '../modules/purchase-returns/route';
import procurementRoutes from '../modules/procurement/route';
import crmRoutes from '../modules/crm/route';
import hrRoutes from '../modules/hr/route';
import equipmentRoutes from '../modules/equipment/route';
import projectRoutes from '../modules/projects/route';
import projectLookupRoutes from '../modules/projects/lookup-route';
import inventoryRoutes from '../modules/inventory/route';
import erpExpansionRoutes from '../modules/erp-expansion/route';
import analyticsRoutes from '../modules/analytics/route';
import apiCompatRoutes from '../modules/api-compat/route';
import syncRoutes from '../modules/sync/route';
import orgRoutes from '../modules/org/route';
import numberingRoutes from '../modules/numbering/route';
import attachmentRoutes from '../modules/attachments/route';
import printingRoutes from '../modules/printing/route';
import subcontractorRoutes from '../modules/subcontractors/route';
import siteRoutes from '../modules/site/route';
import contractsRoutes from '../modules/contracts/route';
import maintenanceRoutes from '../modules/maintenance/route';
import tendersRoutes from '../modules/tenders/route';
import risksRoutes from '../modules/risks/route';
import schedulingRoutes from '../modules/scheduling/route';
import qualitySafetyRoutes from '../modules/quality-safety/route';

const router = Router();

router.use('/auth', authRoutes);
router.use('/central/auth', authRoutes);
router.use('/central', centralRoutes);
router.use('/sync', syncRoutes);
router.use('/org', orgRoutes);
router.use('/users', usersRoutes);
router.use('/roles', rolesRoutes);
router.use('/settings', settingsRoutes);
router.use('/settings/numbering', numberingRoutes);
router.use('/attachments', attachmentRoutes);
router.use('/documents', attachmentRoutes);
router.use('/printing', printingRoutes);
router.use('/subcontractors', subcontractorRoutes);
router.use('/site', siteRoutes);
router.use('/quality/site', siteRoutes);
router.use('/contracts', contractsRoutes);
router.use('/contracts/customers', customersRoutes);
router.use('/contracts/crm', crmRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/maintenance/assets', assetRoutes);
router.use('/maintenance/suppliers', suppliersRoutes);
router.use('/maintenance/projects', projectLookupRoutes);
router.use('/tenders', tendersRoutes);
router.use('/tenders/crm', crmRoutes);
router.use('/risks', risksRoutes);
router.use('/risks/users', usersRoutes);
router.use('/scheduling', schedulingRoutes);
router.use('/scheduling/projects', projectLookupRoutes);
router.use('/', qualitySafetyRoutes);
router.use('/fiscal', fiscalRoutes);
router.use('/fiscal-years', fiscalYearsRoutes);
router.use('/periods', periodsRoutes);
router.use('/accounting', accountingRoutes);
router.use('/accounting/reports', reportRoutes);
router.use('/accounting/periods', periodsRoutes);
router.use('/accounting/journals', journalRoutes);
router.use('/accounting/accounts', accountRoutes);
router.use('/accounts', accountRoutes);
router.use('/journals', journalRoutes);
router.use('/parties', partiesRoutes);
router.use('/customers', customersRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/quotes', quotesRoutes);
router.use('/sales-returns', salesReturnsRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/banks', bankRoutes);
router.use('/bank-transactions', bankTransactionsRoutes);
router.use('/assets', assetRoutes);
router.use('/asset-categories', assetCategoriesRoutes);
router.use('/depreciation', depreciationRoutes);
router.use('/budgets', budgetRoutes);
router.use('/budgets/accounts', accountRoutes);
router.use('/taxes', taxRoutes);
router.use('/tax-codes', taxCodesRoutes);
router.use('/tax-declarations', taxDeclarationsRoutes);
router.use('/purchase-orders', purchaseOrdersRoutes);
router.use('/purchase-requests', purchaseRequestsRoutes);
router.use('/purchase-returns', purchaseReturnsRoutes);
router.use('/procurement', procurementRoutes);
router.use('/procurement/suppliers', suppliersRoutes);
router.use('/procurement/projects', projectLookupRoutes);
router.use('/crm', crmRoutes);
router.use('/hr', hrRoutes);
router.use('/equipment', equipmentRoutes);
router.use('/equipment/projects', projectLookupRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/inventory/org', orgRoutes);
router.use('/inventory/reports', reportRoutes);
router.use('/inventory/projects', projectLookupRoutes);
router.use('/', projectRoutes);
router.use('/', inventoryRoutes);
router.use('/reports', reportRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/', apiCompatRoutes);
router.use('/', erpExpansionRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/', partiesRoutes);

export default router;
