import { Router } from 'express';
import authRoutes from '../modules/auth/route';
import usersRoutes from '../modules/users/route';
import rolesRoutes from '../modules/roles/route';
import settingsRoutes from '../modules/settings/route';
import fiscalRoutes from '../modules/fiscal/route';
import accountRoutes from '../modules/accounts/route';
import journalRoutes from '../modules/journals/route';
import partiesRoutes from '../modules/parties/route';
import customersRoutes from '../modules/customers/route';
import suppliersRoutes from '../modules/suppliers/route';
import quotesRoutes from '../modules/quotes/route';
import salesReturnsRoutes from '../modules/sales-returns/route';
import invoiceRoutes from '../modules/invoices/route';
import paymentRoutes from '../modules/payments/route';
import bankRoutes from '../modules/banks/route';
import assetRoutes from '../modules/assets/route';
import budgetRoutes from '../modules/budgets/route';
import taxRoutes from '../modules/taxes/route';
import reportRoutes from '../modules/reports/route';
import auditRoutes from '../modules/audit-logs/route';
import fiscalYearsRoutes from '../modules/fiscal-years/route';
import periodsRoutes from '../modules/periods/route';
import bankTransactionsRoutes from '../modules/bank-transactions/route';
import assetCategoriesRoutes from '../modules/asset-categories/route';
import depreciationRoutes from '../modules/depreciation/route';
import centralRoutes from '../modules/central/route';
import taxCodesRoutes from '../modules/tax-codes/route';
import taxDeclarationsRoutes from '../modules/tax-declarations/route';
import purchaseOrdersRoutes from '../modules/purchase-orders/route';
import purchaseReturnsRoutes from '../modules/purchase-returns/route';
import erpExpansionRoutes from '../modules/erp-expansion/route';
import analyticsRoutes from '../modules/analytics/route';
import apiCompatRoutes from '../modules/api-compat/route';
import syncRoutes from '../modules/sync/route';
import orgRoutes from '../modules/org/route';
import numberingRoutes from '../modules/numbering/route';
import attachmentRoutes from '../modules/attachments/route';

const router = Router();

router.use('/auth', authRoutes);
router.use('/central', centralRoutes);
router.use('/sync', syncRoutes);
router.use('/org', orgRoutes);
router.use('/users', usersRoutes);
router.use('/roles', rolesRoutes);
router.use('/settings', settingsRoutes);
router.use('/settings/numbering', numberingRoutes);
router.use('/attachments', attachmentRoutes);
router.use('/documents', attachmentRoutes);
router.use('/fiscal', fiscalRoutes);
router.use('/fiscal-years', fiscalYearsRoutes);
router.use('/periods', periodsRoutes);
router.use('/accounts', accountRoutes);
router.use('/journals', journalRoutes);
router.use('/parties', partiesRoutes);
router.use('/customers', customersRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/quotes', quotesRoutes);
router.use('/sales-returns', salesReturnsRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/banks', bankRoutes);
router.use('/bank-transactions', bankTransactionsRoutes);
router.use('/assets', assetRoutes);
router.use('/asset-categories', assetCategoriesRoutes);
router.use('/depreciation', depreciationRoutes);
router.use('/budgets', budgetRoutes);
router.use('/taxes', taxRoutes);
router.use('/tax-codes', taxCodesRoutes);
router.use('/tax-declarations', taxDeclarationsRoutes);
router.use('/purchase-orders', purchaseOrdersRoutes);
router.use('/purchase-returns', purchaseReturnsRoutes);
router.use('/reports', reportRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/', apiCompatRoutes);
router.use('/', erpExpansionRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/', partiesRoutes);

export default router;
