import { Router } from 'express';
import authRoutes from '../modules/auth/route';
import usersRoutes from '../modules/users/route';
import rolesRoutes from '../modules/roles/route';
import settingsRoutes from '../modules/settings/route';
import fiscalRoutes from '../modules/fiscal/route';
import accountRoutes from '../modules/accounts/route';
import journalRoutes from '../modules/journals/route';
import partiesRoutes from '../modules/parties/route';
import customersRoutes from '../modules/customers/route';
import suppliersRoutes from '../modules/suppliers/route';
import quotesRoutes from '../modules/quotes/route';
import salesReturnsRoutes from '../modules/sales-returns/route';
import invoiceRoutes from '../modules/invoices/route';
import paymentRoutes from '../modules/payments/route';
import bankRoutes from '../modules/banks/route';
import assetRoutes from '../modules/assets/route';
import budgetRoutes from '../modules/budgets/route';
import taxRoutes from '../modules/taxes/route';
import reportRoutes from '../modules/reports/route';
import auditRoutes from '../modules/audit-logs/route';
import fiscalYearsRoutes from '../modules/fiscal-years/route';
import periodsRoutes from '../modules/periods/route';
import bankTransactionsRoutes from '../modules/bank-transactions/route';
import assetCategoriesRoutes from '../modules/asset-categories/route';
import depreciationRoutes from '../modules/depreciation/route';
import taxCodesRoutes from '../modules/tax-codes/route';
import taxDeclarationsRoutes from '../modules/tax-declarations/route';
import purchaseOrdersRoutes from '../modules/purchase-orders/route';
import purchaseReturnsRoutes from '../modules/purchase-returns/route';
import erpExpansionRoutes from '../modules/erp-expansion/route';
import analyticsRoutes from '../modules/analytics/route';
import apiCompatRoutes from '../modules/api-compat/route';
import budgetingRoutes from '../modules/budgeting/route';
import controlCenterRoutes from '../modules/control-center/route';
import crmRoutes from '../modules/crm/route';
import contractsRoutes from '../modules/contracts/route';
import dashboardRoutes from '../modules/dashboard/route';
import documentsRoutes from '../modules/documents/route';
import financeRoutes from '../modules/finance/route';
import hrRoutes from '../modules/hr/route';
import inventoryRoutes from '../modules/inventory/route';
import maintenanceRoutes from '../modules/maintenance/route';
import platformRoutes from '../modules/platform/route';
import profileRoutes from '../modules/profile/route';
import platformAdminRoutes from '../modules/platform-admin/route';
import printingRoutes from '../modules/printing/route';
import procurementRoutes from '../modules/procurement/route';
import projectsRoutes from '../modules/projects/route';
import qualityRoutes from '../modules/quality/route';
import riskRoutes from '../modules/risk/route';
import schedulingRoutes from '../modules/scheduling/route';
import siteOpsRoutes from '../modules/site-ops/route';
import subcontractorsRoutes from '../modules/subcontractors/route';
import tenderingRoutes from '../modules/tendering/route';
import workspaceRoutes from '../modules/workspace/route';
import yearCloseRoutes from '../modules/year-close/route';

const router = Router();

router.use('/auth', authRoutes);
router.use('/finance', financeRoutes);
router.use('/crm', crmRoutes);
router.use('/hr', hrRoutes);
router.use('/projects', projectsRoutes);
router.use('/procurement', procurementRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/control-center', controlCenterRoutes);
router.use('/contracts', contractsRoutes);
router.use('/tendering', tenderingRoutes);
router.use('/subcontractors', subcontractorsRoutes);
router.use('/site-ops', siteOpsRoutes);
router.use('/quality', qualityRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/budgeting', budgetingRoutes);
router.use('/risk', riskRoutes);
router.use('/scheduling', schedulingRoutes);
router.use('/printing', printingRoutes);
router.use('/platform', platformRoutes);
router.use('/documents', documentsRoutes);
router.use('/users', usersRoutes);
router.use('/roles', rolesRoutes);
router.use('/settings', settingsRoutes);
router.use('/fiscal', fiscalRoutes);
router.use('/fiscal-years', fiscalYearsRoutes);
router.use('/periods', periodsRoutes);
router.use('/accounts', accountRoutes);
router.use('/journals', journalRoutes);
router.use('/parties', partiesRoutes);
router.use('/customers', customersRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/quotes', quotesRoutes);
router.use('/sales-returns', salesReturnsRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/banks', bankRoutes);
router.use('/bank-transactions', bankTransactionsRoutes);
router.use('/assets', assetRoutes);
router.use('/asset-categories', assetCategoriesRoutes);
router.use('/depreciation', depreciationRoutes);
router.use('/budgets', budgetRoutes);
router.use('/taxes', taxRoutes);
router.use('/tax-codes', taxCodesRoutes);
router.use('/tax-declarations', taxDeclarationsRoutes);
router.use('/purchase-orders', purchaseOrdersRoutes);
router.use('/purchase-returns', purchaseReturnsRoutes);
router.use('/reports', reportRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/', dashboardRoutes);
router.use('/', profileRoutes);
router.use('/', platformAdminRoutes);
router.use('/', workspaceRoutes);
router.use('/', yearCloseRoutes);
router.use('/', apiCompatRoutes);
router.use('/', erpExpansionRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/', partiesRoutes);

export default router;
